apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-frontend
  labels:
    app: app

spec:
  minReplicas: 1
  maxReplicas: 5

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  targetCPUUtilizationPercentage: 30
